development:
  sessions:
    default:
      database: toy_tracker
      hosts:
        - localhost:27017

production:
  sessions:
    default:
      database: toy_tracker
      uri: <%= ENV['MONGOHQ_URL'] %>
