development:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

test:
  sessions:
    default:
      database: mongoid_test
      hosts: 
        - localhost:27017
      
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
