development:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>

test:
  sessions:
    default:
      host: localhost
      database: mongoid_test
      
production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
